#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

color0=#3B4252
color4=#D8DEE9

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config border_width        0
bspc config top_padding         2
bspc config right_padding       2
bspc config left_padding        2
bspc config bottom_padding      2
bspc config window_gap          2
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config focused_border_color "$color0"
bspc config normal_border_color  "$color0"
bspc config active_border_color  "$color0"
bspc config presel_feedback_color "$color4"
bspc config split_ratio          0.50
bspc config borderless_monocle   true  
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

pkill polybar
pkill flameshot
pkill dunst
pkill nm-applet

feh --bg-fill ~/.wallpaper.png
bash ~/.config/polybar/launch.sh &
flameshot &
dunst &
nm-applet &
compton &
